### ISSUE TITLE
Spec finder should find lib/gem_name/file.rb => spec spec/gem_name/file_spec.rb

### ISSUE THREAD

**Issue by fphilipe** [skwp/vim-ruby-conque#14]
It seems to be standard to not have a lib folder in the specs folder in gems since lib is often the only folder inside the project.

It would be great if spec-finder could also find as follow:

```
lib/gem_name/file.rb => spec spec/gem_name/file_spec.rb
```

**Comment by skwp** [comment]
Please fix and open a pull request :)
