### ISSUE TITLE
running with Zeus

### ISSUE THREAD

**Issue by abacha** [skwp/vim-ruby-conque#22]
I'm trying to use this plugin with gem zeus but I can't because of the '--color' option:

`let g:ruby_conque_rspec_runner='zeus rspec'`

```
/home/duke/.rvm/gems/ruby-1.9.3-p194@bigbang/gems/zeus-0.13.2/lib/zeus/m.rb:188:in `block in parse_options!': invalid option: --color (OptionParser::InvalidOption)
        from /home/duke/.rvm/gems/ruby-1.9.3-p194@bigbang/gems/zeus-0.13.2/lib/zeus/m.rb:162:in `new'
        from /home/duke/.rvm/gems/ruby-1.9.3-p194@bigbang/gems/zeus-0.13.2/lib/zeus/m.rb:162:in `parse_options!'
        from /home/duke/.rvm/gems/ruby-1.9.3-p194@bigbang/gems/zeus-0.13.2/lib/zeus/m.rb:134:in `parse'
...
```

**Comment by incorvia** [comment]
@abacha Did you find a work around?  Same issue.

**Comment by abacha** [comment]
I think I've removed `--color` from the plugin command and it worked
but I don't know anymore, I gave up using any kind of spec runner on vim, I went for guard

**Comment by skwp** [comment]
I'm using spring right now..Not integrated with vim yet. I'm trying to understand its quirks first.
