### ISSUE TITLE
why not use a quickfix window?

### ISSUE THREAD

**Issue by AlphaLiu** [skwp/vim-ruby-conque#6]
Why would you choose to open a buffer instead of a quickfix? And why the result window stay in insert mode? I think normal mode would be better.

**Comment by skwp** [comment]
The insert mode is ConqueTerm's thing and I haven't been able to figure out how to make it exit. I suppose I can send an esc to the buffer..will try that

As far as buffer vs quickfix, this is again ConqueTerm, which is a fully running shell within vim. Which is great for when you have longer running tests so they don't block your UI. If you want something that uses quickfix, I think maybe Specky does but not sure 100%.

**Comment by AlphaLiu** [comment]
OK, I see! Thanks for replying
